### ISSUE TITLE
"Accept header absent and forced to application/json" log spam

### ISSUE THREAD

**Issue by dharmab** [Azure/msrest-for-python#109]
#102 introduced code which ensured the "Accept" header is always set to "application/json". However, it also introduced a WARNING level log that causes a lot of spam in applications using the Azure SDK.

This makes it really had to read application logs; here's an example of an Azure deployment in Jenkins:

![image](https://user-images.githubusercontent.com/4450708/41667525-6f5d8d5a-746a-11e8-81f1-0b89141c263b.png)

**Comment by lmazuel** [comment]
Hum, I guess you're right. With new SDK, this warning should not be seen, but since there is more "old" SDKs released than new one, that's probably fair.
Let's do a debug for now as you suggest, but in a 6 months timeframe, I should put him back to "warning". This is to warn about a wrong assumption made by old generators that the entire world is JSON (even if it's not). New generated SDKs are more precise, and able to deal with XML.
Thanks for the PR!
